apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: quarkus-native
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: contextDir
        description: The location of the path to run s2i from.
        default: .
      - name: tlsVerify
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
      - name: destinationImageName
        description: The destination image name that will be pushed to container registry
        default: "${outputs.resources.image.url}"
      - name: mavenMirrorUrl
        description: The Maven Mirror to use
        default: 'https://repo1.maven.org/maven2'
      - name: dockerfilePath
        description: The native build docker file path relative to the contextDir
        default: src/main/docker/Dockerfile.native
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: native-build
      imagePullPolicy: Always
      image: quay.io/quarkus/ubi-quarkus-native-s2i:19.1.2
      env: 
        - name: MAVEN_MIRROR_URL
          value: "${inputs.params.mavenMirrorUrl}"
        - name: TLSVERIFY
          value: "${inputs.params.tlsVerify}"
        - name: WORK_DIR
          value: /workspace/source/${inputs.params.contextDir}
        - name: MVN_CMD_ARGS
          value: "-Pnative clean package -DskipTests"
      args: ["/usr/local/bin/maven-run.sh"]
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 6Gi
          cpu: 4
        requests:
          memory: 4Gi
          cpu: 2
    - name: build
      image: quay.io/buildah/stable
      workingdir: /workspace/source/${inputs.params.contextDir}
      command: ['buildah', 'bud', '--tls-verify=${inputs.params.tlsVerify}', '--layers','-f', '/workspace/source/${inputs.params.contextDir}/${inputs.params.dockerfilePath}', '-t', '${inputs.params.destinationImageName}', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 6Gi
          cpu: 4
        requests:
          memory: 4Gi
          cpu: 2
    - name: push
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--tls-verify=${inputs.params.tlsVerify}', '${inputs.params.destinationImageName}', 'docker://${inputs.params.destinationImageName}']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
