apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: quarkus-native
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: PATH_CONTEXT
        description: The location of the path to run s2i from.
        default: .
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
      - name: DESTINATION_IMAGE_NAME
        description: The destination image name that will be pushed to container registry
        default: "${outputs.resources.image.url}"
      - name: MAVEN_MIRROR_URL
        description: The Maven Mirror to use
        default: 'https://repo1.maven.org/maven2'
      - name: builderImage
        description: The s2i image to be used as builder image 
        default: 'quay.io/quarkus/ubi-quarkus-native-s2i:19.0.2'
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: mvn-build
      image: "${inputs.params.builderImage}"
      env: 
        - name: SRC_DIR
          value: /workspace/source/${inputs.params.PATH_CONTEXT}
        # - name: MAVEN_MIRROR_URL
        #   value: "${inputs.params.MAVEN_MIRROR_URL}"
      workingdir: /workspace/source/${inputs.params.PATH_CONTEXT}
      command: ['/usr/local/s2i/assemble']
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 6Gi
          cpu: 4
        requests:
          memory: 4Gi
          cpu: 2
    - name: image-build
      image: quay.io/buildah/stable
      workingdir: /workspace/source/${inputs.params.PATH_CONTEXT}
      command: ['buildah', 'bud', '--tls-verify=${inputs.params.TLSVERIFY}', '--layers','--build-arg=MAVEN_MIRROR_URL=${inputs.params.MAVEN_MIRROR_URL}', '-f', "/workspace/source/${inputs.params.PATH_CONTEXT}/src/main/docker/Dockerfile.native", '-t', '${inputs.params.DESTINATION_IMAGE_NAME}', '.']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push
      image: quay.io/buildah/stable
      command: ['buildah', 'push', '--tls-verify=${inputs.params.TLSVERIFY}', '${inputs.params.DESTINATION_IMAGE_NAME}', 'docker://${inputs.params.DESTINATION_IMAGE_NAME}']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}