apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-s2i-quarkus-
spec:
  taskRef:
    name: s2i-quarkus
  inputs:
    resources:
      - name: source
        resourceRef:
          name: customer-git
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "customer/java/quarkus"
      - name: MAVEN_MIRROR_URL
        value: 'http://nexus3.labs:8081/nexus/content/groups/public'
  outputs:
    resources:
      - name: image
        resourceRef:
          name: customer-openshift-image
